apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: zydusappmigrate 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zydusappmigrate 
    spec:
      containers:
        - name: zydusappmigrate 
          image: cadilla.azurecr.io/zydusappmigrate
          ports:
          - containerPort: 80